name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: opentelemetry, protobuf
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run formatting check
        run: composer format:check

      - name: Run static analysis
        run: composer analyze

      - name: Run unit tests
        run: composer test

  e2e:
    name: E2E tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: opentelemetry, protobuf
          coverage: none

      - name: Run Docker E2E tests
        run: composer test:e2e:docker
